// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppNav: typeof import('./components/AppNav.vue')['default']
    DaisyButton: typeof import('daisy-ui-kit')['DaisyButton']
    DaisyButtonGroup: typeof import('daisy-ui-kit')['DaisyButtonGroup']
    DaisyCard: typeof import('daisy-ui-kit')['DaisyCard']
    DaisyCardBody: typeof import('daisy-ui-kit')['DaisyCardBody']
    DaisyDropdown: typeof import('daisy-ui-kit')['DaisyDropdown']
    DaisyDropdownContent: typeof import('daisy-ui-kit')['DaisyDropdownContent']
    DaisyFlex: typeof import('daisy-ui-kit')['DaisyFlex']
    DaisyFormControl: typeof import('daisy-ui-kit')['DaisyFormControl']
    DaisyHero: typeof import('daisy-ui-kit')['DaisyHero']
    DaisyHeroContent: typeof import('daisy-ui-kit')['DaisyHeroContent']
    DaisyLink: typeof import('daisy-ui-kit')['DaisyLink']
    DaisyMenu: typeof import('daisy-ui-kit')['DaisyMenu']
    DaisyMenuItem: typeof import('daisy-ui-kit')['DaisyMenuItem']
    DaisyNavbar: typeof import('daisy-ui-kit')['DaisyNavbar']
    DaisyNavbarCenter: typeof import('daisy-ui-kit')['DaisyNavbarCenter']
    DaisyNavbarEnd: typeof import('daisy-ui-kit')['DaisyNavbarEnd']
    DaisyNavbarStart: typeof import('daisy-ui-kit')['DaisyNavbarStart']
    DaisySelect: typeof import('daisy-ui-kit')['DaisySelect']
    DaisyText: typeof import('daisy-ui-kit')['DaisyText']
    DaisyTooltip: typeof import('daisy-ui-kit')['DaisyTooltip']
    FormControlText: typeof import('./components/FormControlText.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
